/**
 * E2E · Smoke
 * Answers one question after every deploy: do the public entry points render
 * without crashing? Runs with fake env in CI, so nothing here may depend on
 * real data. Flows that need a logged-in user live in their own spec files.
 */
import { expect, test } from "@playwright/test"

test.describe("public pages", () => {
  test("home shows the value proposition and a way in", async ({ page }) => {
    const pageErrors: Error[] = []
    page.on("pageerror", (error) => pageErrors.push(error))

    await page.goto("/")

    await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
    await expect(page.getByRole("link", { name: /mentor/i }).first()).toBeVisible()
    // An uncaught exception during hydration is invisible in a screenshot
    // but breaks clicks; fail on it explicitly.
    expect(pageErrors).toEqual([])
  })

  test("quiz renders its first step", async ({ page }) => {
    await page.goto("/quiz")
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
  })

  test("mentors catalogue page renders", async ({ page }) => {
    const response = await page.goto("/mentors")
    expect(response?.ok()).toBe(true)
  })
})

test.describe("agent-facing surface", () => {
  // llms.txt is how LLM crawlers and agents learn what MENVO is (generated by
  // `npm run build:kb`). If it disappears, agents silently lose context.
  test("llms.txt is served with content", async ({ request }) => {
    const response = await request.get("/llms.txt")
    expect(response.ok()).toBe(true)
    expect((await response.text()).length).toBeGreaterThan(200)
  })
})
